### PR TITLE
feat: add ingressClass

### PR DESCRIPTION
**Pull request by cin-logan**
## What this PR does / why we need it:
Since to EKS version 1.22, deprecated nginx kubernetes.io/ingress.class and we need to upgrade to using ingressClassName then i have create PR to do this 
## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [ ] PR only contains changes for one chart

### CODE REVIEW

**Comment by haorenfsa** [comment]
Hi @cin-logan, it would be better to add an default empty string value in `charts/milvus/values.yaml`, so that in other people can easily search for this field if they need it. It can also make the to auto generated documents better, like in https://artifacthub.io/packages/helm/milvus/milvus?modal=values.

**Comment by cin-logan** [comment]
could you help me to review it again ? thanks @haorenfsa

**Comment by haorenfsa** [comment]
@cin-logan looks good, please bump the chart version to 4.2.1. And we're ready to merge it.

**Comment by cin-logan** [comment]
Sorry for the inconvenience, I have force-pushed again 😢. Could you check it, @haorenfsa

**Review by haorenfsa — APPROVED** [review]

**Pull request merged**
