### PR TITLE
K8s based podDisruptionBudget for etcd

### PR DESCRIPTION
**Pull request by Rachit-Chaudhary11**
## What this PR does / why we need it:
Higher versions of Kubernetes fail to work with etcd **policy/v1beta1**, hence a configurable policy based on the kubernetes version is needed.

**Error Message**: No matches for kind "PodDisruptionBudget" in version "policy/v1beta1".

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by Rachit-Chaudhary11** [comment]
/assign @zwd1208 
@haorenfsa please verify

**Comment by haorenfsa** [comment]
@Rachit-Chaudhary11 Lint not pass: https://github.com/zilliztech/milvus-helm/actions/runs/8214018017/job/22466048776?pr=74

Cloud you post it here what changes did you do to the etcd chart? since it's a binary in the repo.

**Comment by Rachit-Chaudhary11** [comment]
> @Rachit-Chaudhary11 Lint not pass: https://github.com/zilliztech/milvus-helm/actions/runs/8214018017/job/22466048776?pr=74
> 
> Could you also post it here what changes did you do to the etcd chart? since it's a binary in the repo.

@haorenfsa I have made the changes to the following files (**_helpers.tpl, pdm.yaml**) inside **etcd-6.3.3.tgz**
Screenshot 2024-03-12 at 8 54 37 PM
Screenshot 2024-03-12 at 8 55 48 PM

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa similar check is done for minio

Refer- https://github.com/zilliztech/milvus-helm/blob/master/charts/minio/templates/_helpers.tpl#L35

**Comment by haorenfsa** [comment]
@Rachit-Chaudhary11 looks the `etcd-6.3.3.tgz` binary is not gzipped:

image

How did you package it? usually we use the command like: `tar -czf etcd-6.3.3.tgz .`

**Comment by Rachit-Chaudhary11** [comment]
> @Rachit-Chaudhary11 looks the `etcd-6.3.3.tgz` binary is not gzipped:
> 
> image
> How did you package it? usually we use the command like: `tar -czf etcd-6.3.3.tgz .`

@haorenfsa I believe I have done the same. May I know what is exactly the issue? 
Basically what I did is unarchieve it and placed it a different place, made the changes, archived it and move the archived folder again back to charts/milvus/charts which invariably replaced this existing tgz for etcd.

**Comment by haorenfsa** [comment]
@Rachit-Chaudhary11 it's packaged, but not archived through gzip, since we can still see the preview of its content.
https://github.com/zilliztech/milvus-helm/blob/0d63040bd493efc3a136d4064591bf5d14c41a1b/charts/milvus/charts/etcd-6.3.3.tgz

The gziped content cannot be previewed, like: https://github.com/zilliztech/milvus-helm/blob/0d63040bd493efc3a136d4064591bf5d14c41a1b/charts/milvus/charts/minio-8.0.17.tgz

**Comment by haorenfsa** [comment]
@Rachit-Chaudhary11 please check if `-z` option is included in your `tar` command

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa please check now. I have re-performed the same command

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa Thank you for the changes. 
As per the suggestion I have zipped the etcd directory again and checked-in. Kindly validate.

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa Thank you for the suggestion.
I have zipped the etcd directory again and checked-in. Kindly validate.

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa kindly validate and merged the PR

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa can you please validate now and provide your approval/ suggestions?

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa @zwd1208 can you please review the changes

**Comment by haorenfsa** [comment]
Hi @Rachit-Chaudhary11 , please squash your commits into 1. and then sign it off.

For squash you can use command:
- `git rebase -i HEAD~11` (you have 11 commits in all)
- then, in the interactive vim: change all the `pick` to `squach`, then save it with `:x`
image



Then you can sign off with `git commit --amend -s`, then update your final commit msg, and save it with `:x`

**Comment by haorenfsa** [comment]
@Rachit-Chaudhary11 Oh, by the way, since we start to maintain the etcd chart. It's better to also track the source code in the repo like we did for minio. Could you please also add an `etcd` folder under `/charts/` with the source code of the etcd chart?

image

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa as suggested I have added the source code but that has invariably caused the helm and other issues above. Is it okay if you can add the source code at your end

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa please check for the above errors due to the addition of the suggested changes.

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa @zwd1208 can you please help in getting this PR merged.

**Comment by haorenfsa** [comment]
Please make sure the checks pass.   image

**Comment by Rachit-Chaudhary11** [comment]
Due to some rebasing issue I am unable to proceed. Closing this PR and creating a new one having exactly the same fixes.

**Pull request closed without merging**
