### PR TITLE
[milvus] S3 miss the region/useVirtualHost settings

### PR DESCRIPTION
**Pull request by orrn**
## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by orrn** [comment]
https://github.com/milvus-io/milvus/compare/v2.2.12...v2.2.13?diff=unified
image
minio settings add region/useVirtualHost

**Comment by LoveEachDay** [comment]
@orrn You'd commit your pr with `git commit -s` to add a dco.

**Comment by orrn** [comment]
> @orrn您可以将您的项目添加到`git commit -s`dco。

I have added dco.

**Review by LoveEachDay — APPROVED** [review]
/lgtm

**Pull request merged**
