### PR TITLE
[milvus-4.1.18] Enabling High Availability for Milvus

### PR DESCRIPTION
**Pull request by Rachit-Chaudhary11**
## What this PR does / why we need it:
By enabling this feature, Milvus Instances will be resilient to failures, ensuring continuous availability and reliability for users. The implementation includes fault-tolerant mechanisms and redundancy configurations to mitigate downtime and main uninterrupted service in the event of node failures or network issues. Overall, this enhancement enhances the robustness and performance of Milvus, providing a more resilient infrastructure for data storage and retrieval.

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by Rachit-Chaudhary11** [comment]
/assign @loveeachday
@haorenfsa kindly validate.

**Comment by haorenfsa** [comment]
Hi @Rachit-Chaudhary11, looks like the previous PR  https://github.com/zilliztech/milvus-helm/pull/56 cloud cover this.

**Comment by Rachit-Chaudhary11** [comment]
Hi @haorenfsa I see that the above PR is created for QueryNode, DataNode, IndexNode and Proxy. While My PR is for the coordinators.

**Comment by Archalbc** [comment]
> Hi @haorenfsa I see that the above PR is created for QueryNode, DataNode, IndexNode and Proxy. While this PR is for the different Milvus Coordinators. Even after merging the above PR the coordinators will still not have the rolling update, which will be handled by this PR

Hi !
Don't you think you should use the same syntax as PR #56  to add strategy  using "with"/"toYaml" ? This will allow users to completely have the freedom to customize this part according to their need.

Another point, using `.Values.DeploymentUpdate` means you force users to use the same strategy for all coords. Since nobody provide great best practices for either coords or nodes, I think we should let users customize each coords at this moment (this is just my opinion ;) )

**Comment by Rachit-Chaudhary11** [comment]
@haorenfsa I am closing this PR as I have created another PR - 68

**Pull request closed without merging**
