### PR TITLE
[milvus] bump attu version to v2.4.7

### PR DESCRIPTION
**Pull request by shanghaikid**
## What this PR does / why we need it:
Attu v2.4.7 was released with two security patches, the user is asking to bump the version here as well. 

https://github.com/zilliztech/attu/issues/622

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by haorenfsa** [comment]
@shanghaikid chart version should also be bumped https://github.com/zilliztech/milvus-helm/blob/master/charts/milvus/Chart.yaml

**Comment by shanghaikid** [comment]
> @shanghaikid chart version should also be bumped https://github.com/zilliztech/milvus-helm/blob/master/charts/milvus/Chart.yaml

done.

**Pull request merged**
