### PR TITLE
add namespace metadata

### PR DESCRIPTION
**Pull request by mchtech**
## What this PR does / why we need it:

`metadata.namespace` is missing in some templates.

this is needed for when helm is used purely as a templating tool,
since helm template does not add the namespace
https://github.com/helm/helm/issues/3553

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] Variables are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [ ] PR only contains changes for one chart

### CODE REVIEW

**Comment by haorenfsa** [comment]
Hi @mchtech, sry for the delay. Please also bump the version before we could merge it.

**Review by haorenfsa — APPROVED** [review]

**Comment by mchtech** [comment]
> Hi @mchtech, sry for the delay. Please also bump the version before we could merge it.

branch synced.

**Comment by haorenfsa** [comment]
@mchtech, sry I missed last version. pleased bump the version again. Thank you very much for your patience!

**Comment by mchtech** [comment]
> @mchtech, sry I missed last version. Please bump the version again. Thank you very much for your patience!

branch synced.

**Pull request merged**
