### PR TITLE
[milvus] Change kafka as default MQ

### PR DESCRIPTION
**Pull request by dongjiang1989**
## What this PR does / why we need it:
Change kafka as default MQ.

Originally posted by https://milvus.io/tools/sizing 

**1 Million of vectors, 128 Dimensions with 512MB segment** 

Pulsar: 
image

kafka:
image

| | Pulsar | kafka |
|--| -- | -- |
| CPU | 40Core | 32Core |
| Memory |167GB | 112GB |
| SSD | 240GB | 150GB |
| Disk | 70GB | 70GB |

## Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [x] Chart Version bumped
- [x] Variables are documented in the README.md
- [x] Title of the PR starts with chart name (e.g. `[mychartname]`)
- [x] PR only contains changes for one chart

### CODE REVIEW

**Comment by haorenfsa** [comment]
Thank you @dongjiang1989  for bring this out. But it's unlikely we change the default MQ, because many people still uses pulsar and will otherwise be affected next time they do update.

**Comment by haorenfsa** [comment]
By the way, if you have more data or collections or instances, pulsar usually cost less in our practice.

**Comment by dongjiang1989** [comment]
> By the way, if you have more data or collections or instances, pulsar usually cost less in our practice.

Thanks. In my business scenario, using kafka lower usage cost (muti instances in one Kubernetes Cluster). 
Is there any chance to `kafka` as default MQ?

**Comment by haorenfsa** [comment]
@dongjiang1989  Sry, it's a no.

**Comment by LoveEachDay** [comment]
@dongjiang1989 You can manually set kafka as your preferences via simple `--set` or specify in `values.yaml`. We'd like to keep pulsar as the default option for milvus cluster.

**Pull request closed without merging**
